services:
  - type: web
    name: ai-textbook-backend
    env: python
    repo: https://github.com/Mustafa-Shams/Ai-textbook.git # Should be automatically detected
    branch: main
    rootDir: ./backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: QDRANT_URL
        sync: false
      - key: NEON_DB_URL
        sync: false
    healthCheckPath: /
